export type ReviewMode='rahp'|'security'|'combined';
export type EvidenceClass='ephemeral'|'referenced'|'durable'|'exemplar';
export type EvidenceContext='normative-spec'|'implementation'|'test'|'deployment'|'governance'|'operational-evidence'|'build-infrastructure'|'documentation'|'example'|'historical';
export type EvidenceAuthority='normative'|'authoritative'|'supporting'|'informative'|'incidental';
export type ResidualStatus='assured'|'controlled'|'finding'|'assurance-gap'|'review-required'|'not-assessed'|'not-applicable';
export interface Evidence { id:string; class:EvidenceClass; description:string; uri?:string; sha256?:string; collected_at?:string; sensitivity?:string }
export interface EvidenceRef {path:string;context:EvidenceContext;authority:EvidenceAuthority;assertion?:string}
export interface EvidenceAssertion {id:string;status:'present'|'absent'|'partial'|'pass'|'fail'|'unknown';evidence?:EvidenceRef[]}
export interface AssuranceEvaluation {proposition:{id:string;subject:string;target?:string};signals:Array<{id:string;type:'risk-indicator'|'control-indicator'|'assurance-indicator'|'contradictory-evidence';confidence:'low'|'medium'|'high';description?:string}>;control_evidence:EvidenceAssertion[];assurance_evidence:EvidenceAssertion[];residual:{status:ResidualStatus;severity?:'informational'|'low'|'medium'|'high'|'critical';reason:string;missing?:string[]}}
export interface RemediationManifest {version:1;assessment_id:string;finding_id:string;owner_plane:{type:string;repository?:string;authority?:string};requested_outcomes:string[];required_evidence:string[];publication:{eligibility:'eligible'|'ineligible'|'needs-triage';mode:'governed'|'manual'|'none';status:'awaiting-approval'|'approved'|'published'|'not-required'|'rejected';uri?:string}}
export interface RetestRecord {version:1;assessment_id:string;previous_finding:string;previous_revision:string;retested_revision:string;outcome:'resolved'|'residual'|'regression'|'inconclusive';closure_evidence:Array<{id:string;result:'pass'|'fail'|'partial'|'not-produced';uri?:string}>}
export interface RahpResult {version:1;assessment:{id:string;key:string;triggers?:string[]};target:{repository:string;reviewed_revision:string;baseline_revision?:string|null;document?:string};mode:ReviewMode;status:'in-progress'|'completed'|'dispositioned';findings:Array<{id:string;title:string;status:string;[k:string]:unknown}>;disposition:{outcome:'pending'|'no-material-assurance-impact'|'findings-raised'|'remediation-requested'|'risk-accepted'|'superseded';summary?:string;decided_at?:string|null};evidence:Evidence[];retest_triggers?:string[];assurance_summary?:Partial<Record<ResidualStatus,number>>;evaluations?:AssuranceEvaluation[];remediations?:RemediationManifest[];retests?:RetestRecord[]}
export interface ValidationResult {valid:boolean;errors:string[]}
const residualStates=new Set<ResidualStatus>(['assured','controlled','finding','assurance-gap','review-required','not-assessed','not-applicable']);
export function summarizeEvaluations(v:AssuranceEvaluation[]=[]):Record<ResidualStatus,number>{const out:any={assured:0,controlled:0,finding:0,'assurance-gap':0,'review-required':0,'not-assessed':0,'not-applicable':0};for(const x of v)if(residualStates.has(x.residual?.status))out[x.residual.status]++;return out}
export function inferResidual(signals:AssuranceEvaluation['signals'],controls:EvidenceAssertion[],assurance:EvidenceAssertion[]):ResidualStatus{const risk=signals.some(x=>x.type==='risk-indicator'),contra=signals.some(x=>x.type==='contradictory-evidence'),cp=controls.some(x=>x.status==='present'),ca=controls.some(x=>x.status==='absent'),tp=assurance.some(x=>x.status==='pass'),tf=assurance.some(x=>x.status==='fail'),partial=assurance.some(x=>x.status==='partial'||x.status==='unknown');if(contra||tf||(risk&&ca))return'finding';if(risk&&cp&&tp)return'controlled';if(risk&&cp&&(partial||!assurance.length))return'assurance-gap';if(risk)return'review-required';if(cp&&tp)return'assured';return'not-assessed'}
export function retestOutcome(previous:ResidualStatus,current:ResidualStatus):RetestRecord['outcome']{const bad=new Set(['finding','assurance-gap','review-required']),good=new Set(['assured','controlled','not-applicable']);if(bad.has(previous)&&good.has(current))return'resolved';if(good.has(previous)&&bad.has(current))return'regression';if(bad.has(current))return'residual';return'inconclusive'}
export function validateResult(v:any):ValidationResult{const e:string[]=[];const req=(c:any,k:string,p='')=>{if(c?.[k]===undefined||c?.[k]===null||c?.[k]==='')e.push(`${p}${k}: required`)};if(!v||typeof v!=='object')return{valid:false,errors:['<root>: must be object']};const allowedRoot=new Set(['version','assessment','target','mode','status','findings','disposition','evidence','retest_triggers','assurance_summary','evaluations','remediations','retests','closure']);for(const k of Object.keys(v))if(!allowedRoot.has(k))e.push(`${k}: additional property not allowed`);if(v.version!==1)e.push('version: must equal 1');req(v,'assessment');req(v,'target');req(v,'mode');req(v,'status');req(v,'findings');req(v,'disposition');req(v,'evidence');if(v.assessment){req(v.assessment,'id','assessment.');req(v.assessment,'key','assessment.')}if(v.target){req(v.target,'repository','target.');req(v.target,'reviewed_revision','target.')}if(!['rahp','security','combined'].includes(v.mode))e.push('mode: invalid');if(!['in-progress','completed','dispositioned'].includes(v.status))e.push('status: invalid');const outcomes=['pending','no-material-assurance-impact','findings-raised','remediation-requested','risk-accepted','superseded'];if(v.disposition&&!outcomes.includes(v.disposition.outcome))e.push('disposition.outcome: invalid');if(v.status==='dispositioned'&&v.disposition?.outcome==='pending')e.push('dispositioned result cannot have pending outcome');if(!Array.isArray(v.findings))e.push('findings: must be array');else for(const[i,f]of v.findings.entries()){req(f,'id',`findings.${i}.`);req(f,'title',`findings.${i}.`);req(f,'status',`findings.${i}.`)}if(!Array.isArray(v.evidence))e.push('evidence: must be array');else for(const[i,x]of v.evidence.entries()){req(x,'id',`evidence.${i}.`);req(x,'class',`evidence.${i}.`);req(x,'description',`evidence.${i}.`);if(x.class==='referenced'){for(const k of['uri','sha256','collected_at','sensitivity'])req(x,k,`evidence.${i}.`);if(x.sha256&&!/^[0-9a-f]{64}$/.test(x.sha256))e.push(`evidence.${i}.sha256: invalid`)}if(x.class==='ephemeral'&&v.status==='dispositioned')e.push(`dispositioned result must not depend on ephemeral evidence ${x.id??'?'}`)}if(v.evaluations!==undefined){if(!Array.isArray(v.evaluations))e.push('evaluations: must be array');else for(const[i,x]of v.evaluations.entries()){req(x,'proposition',`evaluations.${i}.`);req(x,'residual',`evaluations.${i}.`);if(x.residual&&!residualStates.has(x.residual.status))e.push(`evaluations.${i}.residual.status: invalid`);if(x.residual)req(x.residual,'reason',`evaluations.${i}.residual.`)}}if(v.assurance_summary&&v.evaluations){const got=summarizeEvaluations(v.evaluations);for(const[k,n]of Object.entries(v.assurance_summary))if((got as any)[k]!==n)e.push(`assurance_summary.${k}: expected ${(got as any)[k]}`)}return{valid:e.length===0,errors:e}}
