#!/usr/bin/env python3
"""Render canonical security-hardening findings YAML into Markdown reports."""
from __future__ import annotations
import argparse, pathlib, re, sys
from typing import Any
try:
    import yaml
except ImportError:
    sys.exit('render_security_reviews.py requires PyYAML: pip install -r requirements.txt')

ROOT=pathlib.Path(__file__).resolve().parent.parent
CATALOGUE_RELATIVE='../../../build/site/catalogue.html'
REFERENCE_FILES={'risks':'risks.yaml','controls':'controls.yaml','guardrails':'guardrails.yaml','assurance_tests':'assurance-tests.yaml'}

def load_yaml(path):
    with path.open(encoding='utf-8') as fh: return yaml.safe_load(fh) or {}

def ref_index():
    out={}
    for kind,fn in REFERENCE_FILES.items():
        for path in [ROOT/'data'/fn, *sorted((ROOT/'instances').glob(f'*/data/{fn}'))]:
          if not path.exists(): continue
          for r in load_yaml(path).get('records') or []:
            rid=str(r.get('id') or '')
            if not rid: continue
            title=r.get('name') or r.get('title')
            if not title and kind=='assurance_tests':
                c=str(r.get('pass_criterion') or '').strip()
                title=(c[:90]+'…' if len(c)>90 else c) if c else 'Assurance test'
            out[rid]={'title':str(title or rid),'href':str(r.get('link') or '')}
    return out
IDX=ref_index()

def external_index():
    out={}
    for r in load_yaml(ROOT/'data'/'external-standards.yaml').get('records') or []:
        rid=str(r.get('id') or '')
        if rid:
            out[rid]=r
    return out
EXT=external_index()

def cell(v:Any)->str:
    if v is None:return '—'
    if isinstance(v,list): v=', '.join(str(x) for x in v)
    return re.sub(r'\s+',' ',str(v).strip()).replace('|','\\|') or '—'

def para(v:Any)->str:
    return re.sub(r'\n{3,}','\n\n',str(v or '').strip()) or '—'

def refs(values):
    if not values:return '—'
    bits=[]
    for rid in values:
        rid=str(rid); rec=IDX.get(rid); title=cell(rec.get('title') if rec else rid)
        if rec:
            href=rec.get('href') or f'{CATALOGUE_RELATIVE}#{rid}'
            bits.append(f'[{rid} — {title}]({href})')
        else:
            bits.append(f'`{rid}`')
    return ', '.join(bits)

def bullets(values):
    return [f'- {para(v)}' for v in (values or [])]

def external_alignment_rows(values):
    rows=[]
    for a in values or []:
        ref=str(a.get('ref') or '')
        std=EXT.get(ref,{})
        title=cell(std.get('title') or ref)
        org=cell(std.get('organization') or '—')
        url=a.get('url') or std.get('url')
        label=f'{org} — {title}'
        source=f'[{label}]({url})' if url else label
        clause=cell(a.get('clause'))
        relationship=cell(a.get('relationship'))
        rationale=cell(a.get('rationale'))
        rows.append(f'| {source} | {clause} | `{relationship}` | {rationale} |')
    return rows

def destination(path:pathlib.Path)->pathlib.Path:
    return path.with_name('COMPOSITION_THREAT_MODEL.md' if path.parent.name=='cross-spec' else 'SECURITY_REVIEW.md')

def render(review):
    target=review.get('target') or {}; against=review.get('reviewed_against') or {}; summary=review.get('summary') or {}; findings=review.get('findings') or []
    lines=[f"# {cell(review.get('title'))}",'',
           '> Generated from [`findings.yaml`](findings.yaml). Do not edit this file by hand. Run `python3 tools/render_security_reviews.py` after changing the canonical record.','',
           '## Review metadata','', '| Field | Value |','|---|---|',
           f"| Review ID | `{cell(review.get('id'))}` |",f"| Status | {cell(review.get('status'))} |",f"| Reviewed on | {cell(review.get('reviewed_on'))} |",f"| Target repository | `{cell(target.get('repository'))}` |",f"| Target version | {cell(target.get('version'))} |",f"| Target commit | `{cell(target.get('commit'))}` |",f"| RAHP version | `{cell(against.get('rahp_version'))}` |",f"| Engine contract | `{cell(against.get('engine_contract'))}` |"]
    if against.get('revalidated_on'): lines.append(f"| Engine/method revalidated on | {cell(against.get('revalidated_on'))} |")
    if against.get('original_rahp_version'): lines.append(f"| Original RAHP version | `{cell(against.get('original_rahp_version'))}` |")
    if against.get('revalidation_scope'): lines.append(f"| Revalidation scope | {cell(against.get('revalidation_scope'))} |")
    if target.get('secondary_commit'): lines.append(f"| Secondary target commit | `{cell(target.get('secondary_commit'))}` |")
    lines += [f"| Source paths | {', '.join(f'`{cell(x)}`' for x in target.get('source_paths') or []) or '—'} |",'',
              '## Overall assessment','',para(summary.get('overall_assessment')),'']
    standards={}
    for f in findings:
        for a in f.get('external_alignment') or []:
            ref=str(a.get('ref') or '')
            if ref: standards[ref]=standards.get(ref,0)+1
    if standards:
        lines += ['## External standards coverage','',
                  'External mappings are evidence links, not claims that the cited organization reviewed or endorsed this RAHP finding. The relationship label distinguishes direct coverage from supporting, analogous, or contextual guidance.','',
                  '| External source | Findings mapped |','|---|---|']
        for ref,count in sorted(standards.items()):
            std=EXT.get(ref,{})
            label=f"{cell(std.get('organization') or '—')} — {cell(std.get('title') or ref)}"
            url=std.get('url')
            source=f'[{label}]({url})' if url else label
            lines.append(f'| {source} | {count} |')
        lines += ['']
    positives=review.get('positive_controls') or []
    if positives:
        lines += ['## Security controls already present',''] + bullets(positives) + ['']
    lines += ['## Finding index','', '| ID | Finding | Severity | Exploitability | Impact | Detectability | Propagation | Primary plane |','|---|---|---|---|---|---|---|---|']
    for f in findings:
        lines.append(f"| `{cell(f.get('id'))}` | {cell(f.get('title'))} | {cell(f.get('severity'))} | {cell(f.get('exploitability'))} | {cell(f.get('impact'))} | {cell(f.get('detectability'))} | {cell(f.get('propagation'))} | `{cell(f.get('primary_control_plane'))}` |")
    lines += ['', '## Detailed findings','']
    for f in findings:
        rahp=f.get('rahp') or {}
        lines += [f"### {cell(f.get('id'))} — {cell(f.get('title'))}",'', '| Field | Value |','|---|---|',
                  f"| Status | {cell(f.get('status'))} |",f"| Severity | {cell(f.get('severity'))} |",f"| Exploitability | {cell(f.get('exploitability'))} |",f"| Impact | {cell(f.get('impact'))} |",f"| Detectability | {cell(f.get('detectability'))} |",f"| Propagation | {cell(f.get('propagation'))} |",f"| Primary control plane | `{cell(f.get('primary_control_plane'))}` |",f"| Secondary planes | {', '.join(f'`{cell(x)}`' for x in f.get('secondary_control_planes') or []) or '—'} |",f"| Attack surface | {cell(f.get('attack_surface'))} |",f"| Security properties | {cell(f.get('security_properties'))} |",f"| RAHP risks | {refs(rahp.get('risks'))} |",f"| RAHP controls | {refs(rahp.get('controls'))} |",f"| RAHP guardrails | {refs(rahp.get('guardrails'))} |",f"| RAHP assurance tests | {refs(rahp.get('assurance_tests'))} |",'']
        portable=rahp.get('portable_assurance') or {}
        if portable:
            lines += ['**Portable v1.1 assurance patterns**','',
                      '| Layer | Patterns |','|---|---|',
                      f"| Harms | {cell(portable.get('harm_patterns'))} |",
                      f"| Risks | {cell(portable.get('risk_patterns'))} |",
                      f"| Controls | {cell(portable.get('control_patterns'))} |",
                      f"| Guardrails | {cell(portable.get('guardrail_patterns'))} |",
                      f"| Assurance | {cell(portable.get('assurance_patterns'))} |",
                      f"| Evidence | {cell(portable.get('evidence_patterns'))} |",'']
        if f.get('external_alignment'):
            lines += ['**External standards alignment**','',
                      '| External source | Clause / control | Relationship | Rationale |',
                      '|---|---|---|---|'] + external_alignment_rows(f.get('external_alignment')) + ['']
        lines += ['**Preconditions**',''] + bullets(f.get('preconditions')) + ['']
        if f.get('evidence'):
            lines += ['**Evidence**','', '| Source | Observation |','|---|---|']
            for e in f['evidence']: lines.append(f"| `{cell(e.get('source'))}` | {cell(e.get('observation'))} |")
            lines += ['']
        lines += ['**Attack / failure path**','',para(f.get('attack')),'','**Existing mitigations**',''] + bullets(f.get('existing_mitigations')) + ['', '**Residual gap**','',para(f.get('residual_gap')),'','**Recommended hardening**','',para(f.get('recommendation')),'','**Verification / closure evidence**',''] + bullets(f.get('verification')) + ['']
    return '\n'.join(lines).rstrip()+'\n'

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); a=ap.parse_args()
    files=sorted(ROOT.glob('examples/security-hardening/**/findings.yaml'))
    stale=[]
    for y in files:
        expected=render((load_yaml(y).get('review') or {})); out=destination(y); current=out.read_text(encoding='utf-8') if out.exists() else ''
        if current!=expected:
            if a.check: stale.append(out.relative_to(ROOT)); print(f'STALE {out.relative_to(ROOT)} — run: python3 tools/render_security_reviews.py')
            else: out.write_text(expected,encoding='utf-8'); print(f'[write] {out.relative_to(ROOT)}')
        else: print(f'[ok] {out.relative_to(ROOT)}')
    if stale:return 1
    print(f"Security-review Markdown {'current' if a.check else 'rendered'}: {len(files)} review file(s).")
    return 0
if __name__=='__main__': raise SystemExit(main())
